/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author Ismael
 */
public class Ejercicio140 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio140
     */
    public Ejercicio140() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Euros = new javax.swing.JTextField();
        Dolares = new javax.swing.JTextField();
        ConversorDolares = new javax.swing.JButton();
        ConversorEuros = new javax.swing.JButton();
        Elegir = new javax.swing.JComboBox<>();
        ConversorMutuo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Euros.setText("Euros");
        Euros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EurosActionPerformed(evt);
            }
        });

        Dolares.setText("Dolares");
        Dolares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DolaresActionPerformed(evt);
            }
        });

        ConversorDolares.setText("Conversor a dolares");
        ConversorDolares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConversorDolaresActionPerformed(evt);
            }
        });

        ConversorEuros.setText("Conversor a euros");
        ConversorEuros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConversorEurosActionPerformed(evt);
            }
        });

        Elegir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Euros", "Dolares" }));
        Elegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElegirActionPerformed(evt);
            }
        });

        ConversorMutuo.setText("ConversorMutuo");
        ConversorMutuo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConversorMutuoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ConversorDolares)
                    .addComponent(Euros, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Dolares, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConversorEuros, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(ConversorMutuo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(Elegir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Euros, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dolares, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(Elegir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConversorDolares)
                    .addComponent(ConversorEuros))
                .addGap(65, 65, 65)
                .addComponent(ConversorMutuo)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EurosActionPerformed

    }//GEN-LAST:event_EurosActionPerformed

    private void DolaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DolaresActionPerformed
        
    }//GEN-LAST:event_DolaresActionPerformed

    private void ConversorDolaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConversorDolaresActionPerformed
        double dineroEuros = Double.parseDouble(Euros.getText());
        double dineroDolares = dineroEuros / 1.07160;
        Dolares.setText(dineroDolares+"");
    }//GEN-LAST:event_ConversorDolaresActionPerformed

    private void ConversorEurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConversorEurosActionPerformed
        double dineroDolares = Double.parseDouble(Dolares.getText());
        double dineroEuros = dineroDolares * 1.07160;
        Euros.setText(dineroEuros+"");
    }//GEN-LAST:event_ConversorEurosActionPerformed

    private void ElegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElegirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ElegirActionPerformed

    private void ConversorMutuoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConversorMutuoActionPerformed
        if (Elegir.getSelectedItem() == "Dolares") {//para seleccionar el iten del combobox
            double dineroEuros = Double.parseDouble(Euros.getText());
            double dineroDolares = dineroEuros / 1.07160;
            Dolares.setText(dineroDolares+"");
        }else{
            double dineroDolares = Double.parseDouble(Dolares.getText());
            double dineroEuros = dineroDolares * 1.07160;
            Euros.setText(dineroEuros+"");
        }
    }//GEN-LAST:event_ConversorMutuoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio140.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio140.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio140.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio140.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio140().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConversorDolares;
    private javax.swing.JButton ConversorEuros;
    private javax.swing.JButton ConversorMutuo;
    private javax.swing.JTextField Dolares;
    private javax.swing.JComboBox<String> Elegir;
    private javax.swing.JTextField Euros;
    // End of variables declaration//GEN-END:variables
}
